app:
  name: scalable-app
  version: 1.0

database:
  type: postgres
  host: localhost
  port: 5432
  username: admin
  password: secret

server:
  host: 0.0.0.0
  port: 8000

features:
  logging: true
  debug: false
